import {
  collegesTable,
  db,
  facultyTable,
  faqsTable,
  newsTable,
  pageContentsTable,
  programsTable,
  settingsTable,
} from "@workspace/db";

const now = new Date().toISOString();

function fixMojibake(value: string): string {
  if (!/[\u00D8\u00D9\u00C3\u00C2]/.test(value)) return value;
  const decoded = Buffer.from(value, "binary").toString("utf8");
  const decodedArabic = (decoded.match(/[\u0600-\u06FF]/g) ?? []).length;
  const originalArabic = (value.match(/[\u0600-\u06FF]/g) ?? []).length;
  if (decodedArabic > originalArabic && !decoded.includes("\uFFFD")) {
    return decoded;
  }
  return value;
}

function normalizeSeedPayload<T>(value: T): T {
  if (typeof value === "string") return fixMojibake(value) as T;
  if (Array.isArray(value)) return value.map((entry) => normalizeSeedPayload(entry)) as T;
  if (value && typeof value === "object") {
    const out: Record<string, unknown> = {};
    for (const [key, entry] of Object.entries(value as Record<string, unknown>)) {
      out[key] = normalizeSeedPayload(entry);
    }
    return out as T;
  }
  return value;
}

function insertSeed(table: Parameters<typeof db.insert>[0], rows: unknown) {
  return db.insert(table).values(normalizeSeedPayload(rows as any) as any);
}
const collegeAcademicProfile = {
  visionAr: "<p>أن تكون الكلية مرجعا تعليميا وبحثيا معتمدا إقليميا في تخصصاتها.</p>",
  visionEn: "<p>To be a regionally recognized academic and research reference in its disciplines.</p>",
  missionAr: "<p>تقديم تعليم تطبيقي وبحث علمي وخدمة مجتمعية من خلال برامج مرتبطة بسوق العمل.</p>",
  missionEn: "<p>To deliver applied education, research, and community service through market-aligned programs.</p>",
  goalsAr: "<ul><li>تطوير برامج أكاديمية معتمدة.</li><li>رفع جودة البحث والابتكار.</li><li>تعزيز الشراكات المهنية.</li></ul>",
  goalsEn: "<ul><li>Develop accredited academic programs.</li><li>Improve research and innovation quality.</li><li>Strengthen professional partnerships.</li></ul>",
  departmentsAr: "<ul><li>قسم البرامج الأساسية.</li><li>قسم البحث والابتكار.</li><li>وحدة التدريب الميداني.</li></ul>",
  departmentsEn: "<ul><li>Core Programs Department.</li><li>Research and Innovation Department.</li><li>Field Training Unit.</li></ul>",
  facilitiesAr: "<ul><li>معامل تعليمية متخصصة.</li><li>قاعات ذكية.</li><li>مركز استشارات وتدريب.</li></ul>",
  facilitiesEn: "<ul><li>Specialized teaching laboratories.</li><li>Smart classrooms.</li><li>Consulting and training center.</li></ul>",
  accreditationAr: "<p>تعمل الكلية وفق معايير الجودة الأكاديمية والاعتماد المؤسسي، مع مراجعة دورية للبرامج ومخرجات التعلم.</p>",
  accreditationEn: "<p>The college follows academic quality and institutional accreditation standards, with periodic review of programs and learning outcomes.</p>",
  deanMessageAr: "<p>نلتزم بتجربة تعليمية واضحة، عادلة، ومتصلة بسوق العمل، ونرحب بالطلاب في بيئة تدعم الإبداع والمسؤولية.</p>",
  deanMessageEn: "<p>We are committed to a clear, fair, and employability-focused learning experience in an environment that supports creativity and responsibility.</p>",
};

const programAcademicProfile = {
  degreeAwardedAr: "درجة البكالوريوس",
  degreeAwardedEn: "Bachelor Degree",
  studyModeAr: "انتظام - حضوري مدعوم بالتعلم الرقمي",
  studyModeEn: "Full-time on campus with digital learning support",
  languageOfInstructionAr: "العربية والإنجليزية حسب المقرر",
  languageOfInstructionEn: "Arabic and English depending on the course",
  objectivesAr: "<ul><li>تخريج متخصصين قادرين على حل مشكلات واقعية.</li><li>تنمية مهارات البحث والعمل الجماعي والتواصل.</li><li>ربط الدراسة بالتدريب وسوق العمل.</li></ul>",
  objectivesEn: "<ul><li>Graduate specialists able to solve real-world problems.</li><li>Develop research, teamwork, and communication skills.</li><li>Connect learning with training and employment needs.</li></ul>",
  learningOutcomesAr: "<ul><li>تحليل المشكلات وتصميم حلول مناسبة.</li><li>استخدام الأدوات والمنهجيات المهنية.</li><li>تطبيق أخلاقيات المهنة ومعايير الجودة.</li></ul>",
  learningOutcomesEn: "<ul><li>Analyze problems and design suitable solutions.</li><li>Use professional tools and methodologies.</li><li>Apply professional ethics and quality standards.</li></ul>",
  curriculumAr: "<ol><li>السنة الأولى: مقررات تأسيسية ومهارات جامعية.</li><li>السنة الثانية: مقررات تخصصية أساسية.</li><li>السنة الثالثة: مسارات اختيارية ومشروعات تطبيقية.</li><li>السنة النهائية: تدريب ومشروع تخرج.</li></ol>",
  curriculumEn: "<ol><li>Year 1: foundation courses and university skills.</li><li>Year 2: core disciplinary courses.</li><li>Year 3: electives and applied projects.</li><li>Final year: internship and graduation project.</li></ol>",
  assessmentMethodsAr: "<ul><li>اختبارات تحريرية وعملية.</li><li>مشروعات فردية وجماعية.</li><li>عروض تقديمية وتقييم مستمر.</li></ul>",
  assessmentMethodsEn: "<ul><li>Written and practical exams.</li><li>Individual and group projects.</li><li>Presentations and continuous assessment.</li></ul>",
  graduationRequirementsAr: "<ul><li>إتمام الساعات المعتمدة بنجاح.</li><li>اجتياز التدريب الميداني.</li><li>تسليم مشروع التخرج.</li></ul>",
  graduationRequirementsEn: "<ul><li>Complete all required credit hours.</li><li>Pass field training.</li><li>Submit the graduation project.</li></ul>",
  internshipAr: "<p>يتضمن البرنامج تدريبا ميدانيا منظما بالتعاون مع شركاء الصناعة ومكاتب التوظيف.</p>",
  internshipEn: "<p>The program includes structured field training with industry partners and career services.</p>",
  accreditationAr: "<p>مصمم وفق معايير الجودة الوطنية ومخرجات تعلم قابلة للقياس، مع مراجعة دورية من لجان أكاديمية ومهنية.</p>",
  accreditationEn: "<p>Designed according to national quality standards and measurable learning outcomes, with periodic academic and professional review.</p>",
};

const eustCollegeProfiles = {
  ai: {
    visionAr: "<p>دعم التميز في علوم الذكاء الاصطناعي وتوظيف المعرفة التقنية لخدمة الاقتصاد والمجتمع.</p>",
    visionEn: "<p>To support excellence in artificial intelligence and use technical knowledge to serve the economy and society.</p>",
    missionAr: "<ol><li>إعداد كوادر قادرة على بناء حلول ذكاء اصطناعي عملية.</li><li>دعم قطاعات الصناعة والأعمال بمهارات الذكاء الاصطناعي.</li><li>تشجيع الابتكار والشركات الناشئة في مجالات التعلم الآلي والروبوتات والبيانات.</li></ol>",
    missionEn: "<ol><li>Prepare talent capable of building practical AI solutions.</li><li>Support industry and business sectors with AI skills.</li><li>Encourage innovation and startups in machine learning, robotics, and data.</li></ol>",
    goalsAr: "<ul><li>تأهيل كوادر في قطاعات الدولة المختلفة على تقنيات الذكاء الاصطناعي.</li><li>تطوير برامج أكاديمية مرتبطة بعلوم الذكاء الاصطناعي.</li><li>تعزيز البحث العلمي في الذكاء الاصطناعي وتطبيقاته.</li><li>بناء شراكات مع مؤسسات وجامعات دولية.</li><li>تقديم الاستشارات التقنية للجهات المهتمة بصناعة القرار والتحول الرقمي.</li></ul>",
    goalsEn: "<ul><li>Qualify talent across sectors in artificial intelligence technologies.</li><li>Develop academic programs related to AI sciences.</li><li>Strengthen research in AI and its applications.</li><li>Build partnerships with international institutions and universities.</li><li>Provide technical consultancy for decision-support and digital transformation entities.</li></ul>",
    departmentsAr: "<ul><li>برمجة الآلة واسترجاع المعلومات.</li><li>الروبوتات والآلات الذكية.</li><li>تكنولوجيا الأنظمة والشبكات المدمجة.</li><li>علوم البيانات.</li><li>برنامج الذكاء الاصطناعي الحيوي.</li></ul>",
    departmentsEn: "<ul><li>Machine Programming and Information Retrieval.</li><li>Robotics and Smart Machines.</li><li>Embedded Network Systems Technology.</li><li>Data Science.</li><li>Bio-Artificial Intelligence Program.</li></ul>",
    facilitiesAr: "<ul><li>معامل روبوتات وأنظمة ذكية.</li><li>معامل إنترنت الأشياء والأنظمة المدمجة.</li><li>معامل بيانات ضخمة وتعلم آلة.</li><li>مشروعات تطبيقية تبدأ من المستويات الأولى.</li></ul>",
    facilitiesEn: "<ul><li>Robotics and intelligent systems labs.</li><li>IoT and embedded systems labs.</li><li>Big data and machine learning labs.</li><li>Applied projects starting from early study levels.</li></ul>",
    deanMessageAr: "<p>تركز الكلية على التعلم العميق، التحول الرقمي، وربط المشروعات التطبيقية باحتياجات المؤسسات والقطاعات الإنتاجية.</p>",
    deanMessageEn: "<p>The faculty focuses on deep learning, digital transformation, and connecting applied projects with institutional and productive-sector needs.</p>",
  },
  islamic: {
    visionAr: "<p>أن تكون الكلية مركزا رائدا في تعليم العربية والدراسات الإسلامية للناطقين بغير العربية ونشر الثقافة العربية والإسلامية عالميا.</p>",
    visionEn: "<p>To be a leading center for teaching Arabic and Islamic studies to non-native speakers and promoting Arabic and Islamic culture globally.</p>",
    missionAr: "<p>إعداد خريجين متميزين في اللغة العربية وعلومها والدراسات الإسلامية، قادرين على التواصل الحضاري والبحث والتعليم وفق قيم أخلاقية ومهنية.</p>",
    missionEn: "<p>To prepare distinguished graduates in Arabic language and Islamic studies who can communicate across cultures, research, and teach within ethical and professional values.</p>",
    goalsAr: "<ol><li>إعداد خريجين قادرين على تعليم العربية والدراسات الإسلامية.</li><li>تنمية مهارات الفهم والتحدث والقراءة والكتابة.</li><li>تعريف الطلاب بالثقافة العربية والقيم الإسلامية في إطار أكاديمي معاصر.</li><li>تأهيل الطلاب للبحث والتعليم والإعلام.</li><li>تطوير مقررات متوافقة مع احتياجات سوق العمل.</li></ol>",
    goalsEn: "<ol><li>Prepare graduates able to teach Arabic and Islamic studies.</li><li>Develop comprehension, speaking, reading, and writing skills.</li><li>Introduce Arabic culture and Islamic values in a contemporary academic framework.</li><li>Qualify students for research, education, and media fields.</li><li>Develop curricula aligned with labor-market needs.</li></ol>",
    departmentsAr: "<ul><li>الدراسات الإسلامية.</li><li>اللغة العربية للناطقين بغيرها.</li><li>علوم القرآن.</li><li>الفقه وأصوله.</li><li>المصارف الإسلامية.</li><li>التاريخ والحضارة الإسلامية.</li></ul>",
    departmentsEn: "<ul><li>Islamic Studies.</li><li>Arabic for Non-Native Speakers.</li><li>Quranic Sciences.</li><li>Jurisprudence and Fundamentals.</li><li>Islamic Banking.</li><li>Islamic History and Civilization.</li></ul>",
    facilitiesAr: "<ul><li>منصات تعليم لغة عربية رقمية.</li><li>مكتبة دراسات شرعية وعربية.</li><li>ورش بحث وتحقيق نصوص.</li><li>حلقات تدريب على التدريس والحوار الثقافي.</li></ul>",
    facilitiesEn: "<ul><li>Digital Arabic language learning platforms.</li><li>Arabic and Islamic studies library.</li><li>Research and text-editing workshops.</li><li>Teaching and intercultural dialogue sessions.</li></ul>",
  },
  nursing: {
    visionAr: "<p>إعداد ممرضين قادرين على تقديم رعاية آمنة وإنسانية ومبنية على الدليل العلمي في بيئات صحية متنوعة.</p>",
    visionEn: "<p>To prepare nurses capable of delivering safe, compassionate, evidence-based care in diverse healthcare settings.</p>",
    missionAr: "<p>توفير تعليم تمريضي تطبيقي يدمج المعرفة السريرية، أخلاقيات المهنة، التواصل، والبحث لتحسين جودة الرعاية.</p>",
    missionEn: "<p>To provide applied nursing education that integrates clinical knowledge, ethics, communication, and research to improve care quality.</p>",
    goalsAr: "<ul><li>تنمية مهارات الرعاية السريرية وسلامة المرضى.</li><li>تدريب الطلاب على العمل ضمن فرق متعددة التخصصات.</li><li>تطوير القدرة على التثقيف الصحي والتواصل الإنساني.</li><li>تعزيز ممارسات الجودة ومكافحة العدوى.</li></ul>",
    goalsEn: "<ul><li>Develop clinical care and patient safety skills.</li><li>Train students for interprofessional teamwork.</li><li>Develop health education and compassionate communication skills.</li><li>Strengthen quality practice and infection control.</li></ul>",
    departmentsAr: "<ul><li>تمريض البالغين.</li><li>تمريض الأمومة والطفولة.</li><li>تمريض صحة المجتمع.</li><li>أساسيات التمريض.</li></ul>",
    departmentsEn: "<ul><li>Adult Nursing.</li><li>Maternal and Child Nursing.</li><li>Community Health Nursing.</li><li>Fundamentals of Nursing.</li></ul>",
    facilitiesAr: "<ul><li>معامل مهارات تمريضية ومحاكاة سريرية.</li><li>تدريب ميداني في مؤسسات صحية.</li><li>ورش سلامة المرضى ومكافحة العدوى.</li></ul>",
    facilitiesEn: "<ul><li>Nursing skills and clinical simulation labs.</li><li>Field training in healthcare institutions.</li><li>Patient safety and infection-control workshops.</li></ul>",
  },
  business: {
    visionAr: "<p>تخريج قادة أعمال قادرين على الإدارة والتحليل وريادة الأعمال في بيئات محلية ودولية.</p>",
    visionEn: "<p>To graduate business leaders capable of management, analysis, and entrepreneurship in local and international environments.</p>",
    missionAr: "<p>تقديم برامج أعمال تجمع بين الإدارة، المحاسبة، التمويل، التسويق، التحول الرقمي، والمهارات القيادية.</p>",
    missionEn: "<p>To offer business programs combining management, accounting, finance, marketing, digital transformation, and leadership skills.</p>",
    goalsAr: "<ul><li>تنمية مهارات التخطيط واتخاذ القرار.</li><li>تأهيل الطلاب لريادة الأعمال وإدارة المشروعات.</li><li>ربط الدراسة بدراسات حالة وسوق العمل.</li><li>تطوير مهارات التحليل المالي والتسويق الرقمي.</li></ul>",
    goalsEn: "<ul><li>Develop planning and decision-making skills.</li><li>Prepare students for entrepreneurship and project management.</li><li>Connect learning with case studies and labor-market needs.</li><li>Develop financial analysis and digital marketing skills.</li></ul>",
    departmentsAr: "<ul><li>الإدارة.</li><li>المحاسبة والتمويل.</li><li>التسويق.</li><li>ريادة الأعمال.</li></ul>",
    departmentsEn: "<ul><li>Management.</li><li>Accounting and Finance.</li><li>Marketing.</li><li>Entrepreneurship.</li></ul>",
    facilitiesAr: "<ul><li>معمل محاكاة أعمال.</li><li>ورش ريادة أعمال.</li><li>تدريب على دراسات حالة ولوحات مؤشرات.</li></ul>",
    facilitiesEn: "<ul><li>Business simulation lab.</li><li>Entrepreneurship workshops.</li><li>Case-study and dashboard training.</li></ul>",
  },
  languages: {
    visionAr: "<p>تأهيل خريجين قادرين على الترجمة والتواصل اللغوي والثقافي في بيئات مهنية متعددة.</p>",
    visionEn: "<p>To prepare graduates capable of translation and linguistic-cultural communication in varied professional contexts.</p>",
    missionAr: "<p>تقديم تعليم لغوي وتطبيقي في الترجمة التحريرية والفورية، التحرير، التواصل، وخدمات اللغة للمؤسسات.</p>",
    missionEn: "<p>To provide applied language education in translation, interpretation, editing, communication, and institutional language services.</p>",
    goalsAr: "<ul><li>تطوير كفاءة لغوية عالية.</li><li>تدريب الطلاب على الترجمة المتخصصة والفورية.</li><li>تنمية الوعي الثقافي والأخلاقيات المهنية.</li><li>تأهيل الطلاب لسوق خدمات اللغة والترجمة.</li></ul>",
    goalsEn: "<ul><li>Develop advanced language proficiency.</li><li>Train students in specialized translation and interpretation.</li><li>Build cultural awareness and professional ethics.</li><li>Prepare students for language-services and translation careers.</li></ul>",
    departmentsAr: "<ul><li>الترجمة التحريرية.</li><li>الترجمة الفورية.</li><li>التحرير اللغوي.</li><li>التواصل الثقافي.</li></ul>",
    departmentsEn: "<ul><li>Translation.</li><li>Interpretation.</li><li>Language Editing.</li><li>Intercultural Communication.</li></ul>",
    facilitiesAr: "<ul><li>معمل ترجمة فورية.</li><li>منصات تدريب على أدوات الترجمة.</li><li>ورش تحرير ومراجعة لغوية.</li></ul>",
    facilitiesEn: "<ul><li>Interpretation lab.</li><li>Translation technology training platforms.</li><li>Editing and proofreading workshops.</li></ul>",
  },
};

const eustCenterPageContents = [
  {
    pageKey: "center-political-economic-studies",
    titleAr: "مركز الدراسات السياسية والاقتصادية",
    titleEn: "Science and Technology Center for Political and Economic Studies",
    contentAr: "<h2>عن المركز</h2><p>مركز متخصص في الدراسات السياسية والاقتصادية، إعداد البحوث، التدريب، ودعم المهارات التحليلية للباحثين والدارسين.</p><h2>المجالات</h2><ul><li>السياسات العامة والتحليل السياسي.</li><li>الاقتصاد التطبيقي والتنمية.</li><li>إعداد التقارير والدراسات المتخصصة.</li><li>ورش تدريبية للباحثين والمهنيين.</li></ul><h2>الفئات المستفيدة</h2><p>طلاب الدراسات العليا، الباحثون، العاملون في المؤسسات، والمهتمون بالتحليل السياسي والاقتصادي.</p>",
    contentEn: "<h2>About the Center</h2><p>A specialist center for political and economic studies, research preparation, training, and analytical skills development.</p><h2>Areas</h2><ul><li>Public policy and political analysis.</li><li>Applied economics and development.</li><li>Specialized reports and studies.</li><li>Training workshops for researchers and professionals.</li></ul><h2>Audience</h2><p>Graduate students, researchers, institutional professionals, and learners interested in political and economic analysis.</p>",
  },
  {
    pageKey: "center-legal-administrative-studies",
    titleAr: "مركز الدراسات القانونية والإدارية",
    titleEn: "Science and Technology Center for Legal and Administrative Studies",
    contentAr: "<h2>عن المركز</h2><p>يدعم المركز الدراسات القانونية والإدارية والتدريب المهني في الإدارة العامة، التشريعات، الحوكمة، والمهارات المؤسسية.</p><h2>الخدمات</h2><ul><li>دورات في الإدارة والقيادة.</li><li>برامج في الصياغة القانونية والحوكمة.</li><li>استشارات وبحوث تطبيقية.</li><li>ورش تطوير للعاملين في المؤسسات.</li></ul>",
    contentEn: "<h2>About the Center</h2><p>The center supports legal and administrative studies and professional training in public administration, legislation, governance, and institutional skills.</p><h2>Services</h2><ul><li>Management and leadership courses.</li><li>Legal drafting and governance programs.</li><li>Consulting and applied research.</li><li>Development workshops for institutional staff.</li></ul>",
  },
  {
    pageKey: "center-arabic-language-teaching",
    titleAr: "مركز تعليم اللغة العربية للناطقين بغيرها",
    titleEn: "Arabic Language Teaching Center for Non-Arabic Speakers",
    contentAr: "<h2>عن المركز</h2><p>مركز متخصص في تعليم اللغة العربية لغير الناطقين بها، وتنمية مهارات الاستماع والتحدث والقراءة والكتابة من مستويات تأسيسية إلى متقدمة.</p><h2>المسارات</h2><ul><li>العربية العامة.</li><li>العربية للأغراض الأكاديمية.</li><li>العربية للإعلام والأعمال.</li><li>مهارات المحادثة والكتابة.</li></ul><h2>المخرجات</h2><p>اكتساب كفاءة لغوية وتواصلية تمكن الدارس من استخدام العربية في الدراسة والعمل والحوار الثقافي.</p>",
    contentEn: "<h2>About the Center</h2><p>A center specialized in teaching Arabic to non-native speakers and developing listening, speaking, reading, and writing skills from foundation to advanced levels.</p><h2>Tracks</h2><ul><li>General Arabic.</li><li>Arabic for academic purposes.</li><li>Arabic for media and business.</li><li>Conversation and writing skills.</li></ul><h2>Outcomes</h2><p>Learners gain linguistic and communicative competence for study, work, and intercultural dialogue.</p>",
  },
  {
    pageKey: "center-language-translation",
    titleAr: "مركز اللغة والترجمة",
    titleEn: "Language and Translation Center",
    contentAr: "<h2>عن المركز</h2><p>يقدم المركز خدمات تدريبية وتطبيقية في الترجمة، التحرير اللغوي، الترجمة الفورية، والمراجعة المهنية.</p><h2>الخدمات</h2><ul><li>تدريب الترجمة التحريرية والمتخصصة.</li><li>ورش الترجمة الفورية.</li><li>التحرير والمراجعة اللغوية.</li><li>التدريب على أدوات وتقنيات الترجمة.</li></ul>",
    contentEn: "<h2>About the Center</h2><p>The center provides training and applied services in translation, editing, interpretation, and professional review.</p><h2>Services</h2><ul><li>Specialized and written translation training.</li><li>Interpretation workshops.</li><li>Language editing and proofreading.</li><li>Training on translation tools and technologies.</li></ul>",
  },
  {
    pageKey: "center-educational-rehabilitation",
    titleAr: "مركز التأهيل التربوي",
    titleEn: "Educational Rehabilitation Center",
    contentAr: "<h2>عن المركز</h2><p>مركز يركز على التأهيل التربوي، إعداد المعلمين، تطوير مهارات التدريس، وتصميم بيئات تعلم فعالة.</p><h2>المجالات</h2><ul><li>استراتيجيات التدريس.</li><li>التقويم وبناء الاختبارات.</li><li>إدارة الصف والتواصل التربوي.</li><li>التعلم الرقمي وتصميم المحتوى.</li></ul>",
    contentEn: "<h2>About the Center</h2><p>A center focused on educational rehabilitation, teacher preparation, teaching skills development, and effective learning environments.</p><h2>Areas</h2><ul><li>Teaching strategies.</li><li>Assessment and test design.</li><li>Classroom management and educational communication.</li><li>Digital learning and content design.</li></ul>",
  },
  {
    pageKey: "center-international-arbitration",
    titleAr: "مركز التحكيم الدولي",
    titleEn: "International Arbitration Center",
    contentAr: "<h2>عن المركز</h2><p>مركز يهتم بالتدريب والتوعية في التحكيم الدولي، تسوية المنازعات، الصياغة، وإدارة إجراءات التحكيم.</p><h2>البرامج</h2><ul><li>مبادئ التحكيم الدولي.</li><li>إجراءات التحكيم وإدارة القضايا.</li><li>صياغة شرط التحكيم.</li><li>محاكاة جلسات التحكيم.</li></ul>",
    contentEn: "<h2>About the Center</h2><p>A center concerned with training and awareness in international arbitration, dispute resolution, drafting, and arbitration procedures.</p><h2>Programs</h2><ul><li>Principles of international arbitration.</li><li>Arbitration procedures and case management.</li><li>Drafting arbitration clauses.</li><li>Mock arbitration sessions.</li></ul>",
  },
  {
    pageKey: "center-sharia-studies",
    titleAr: "مركز الدراسات الشرعية",
    titleEn: "Science and Technology Center for Sharia Studies",
    contentAr: "<h2>عن المركز</h2><p>مركز يعنى بالدراسات الشرعية، التدريب البحثي، علوم القرآن، الفقه، والقضايا المعاصرة في إطار أكاديمي منظم.</p><h2>المحاور</h2><ul><li>علوم القرآن والتفسير.</li><li>الفقه وأصوله.</li><li>الدراسات الإسلامية المعاصرة.</li><li>مهارات البحث والتحقيق.</li></ul>",
    contentEn: "<h2>About the Center</h2><p>A center for Sharia studies, research training, Quranic sciences, jurisprudence, and contemporary issues within an organized academic framework.</p><h2>Themes</h2><ul><li>Quranic sciences and interpretation.</li><li>Jurisprudence and fundamentals.</li><li>Contemporary Islamic studies.</li><li>Research and textual scholarship skills.</li></ul>",
  },
].map((page) => ({
  ...page,
  metaTitleAr: `${page.titleAr} | الجامعة الأوروبية للعلوم والتكنولوجيا`,
  metaTitleEn: `${page.titleEn} | European University of Science and Technology`,
  metaDescriptionAr: `تفاصيل ${page.titleAr} في الجامعة الأوروبية للعلوم والتكنولوجيا.`,
  metaDescriptionEn: `${page.titleEn} details at the European University of Science and Technology.`,
  status: "published" as const,
  publishedAt: now,
}));

async function upsertSettings() {
  const values = {
    universityNameAr: "الجامعة الأوروبية للعلوم والتكنولوجيا",
    universityNameEn: "European University of Science and Technology",
    taglineAr: "بوابة أكاديمية حديثة للكليات والبرامج والمراكز العلمية",
    taglineEn: "A modern academic portal for colleges, programs, and research centers",
    logoUrl: "/branding/eust-logo.svg",
    phone: "800 388 80 90",
    email: "info@eust.uk",
    addressAr: "128 سيتي رود، لندن، المملكة المتحدة EC1V 2NX",
    addressEn: "128 City Road, London, United Kingdom, EC1V 2NX",
    facebookUrl: "https://www.facebook.com/",
    twitterUrl: "https://x.com/",
    linkedinUrl: "https://linkedin.com/",
    youtubeUrl: "https://youtube.com/",
    defaultMetaTitleAr: "الجامعة الأوروبية للعلوم والتكنولوجيا | الكليات والبرامج الأكاديمية",
    defaultMetaTitleEn: "European University of Science and Technology | Colleges & Academic Programs",
    defaultMetaDescriptionAr: "بوابة الجامعة الأوروبية للعلوم والتكنولوجيا للكليات والبرامج والمراكز والمجلات والخدمات الأكاديمية.",
    defaultMetaDescriptionEn: "European University of Science and Technology portal for colleges, programs, centers, journals, and academic services.",
    defaultOgImageUrl: "/opengraph.jpg",
    heroDescriptionAr: "استكشف الكليات والبرامج والخدمات الجامعية، وتابع الأخبار والفعاليات، وابدأ رحلة القبول من واجهة حديثة وسهلة الاستخدام.",
    heroDescriptionEn: "Explore colleges, programs, and services, follow news and events, and start admissions from a modern, easy interface.",
    ctaTitleAr: "ابدأ رحلتك الأكاديمية اليوم",
    ctaTitleEn: "Start Your Academic Journey Today",
    ctaDescriptionAr: "انضم إلى مجتمع جامعي يضع المعرفة والخدمة وتجربة الطالب في المقدمة.",
    ctaDescriptionEn: "Join a university community built around knowledge, service, and student experience.",
    totalStudents: 18450,
    yearsOfExcellence: 28,
    researchPapers: 3650,
    admissionRequirementsAr:
      "<ul><li>شهادة الثانوية العامة أو ما يعادلها.</li><li>استيفاء الحد الأدنى للقبول حسب البرنامج.</li><li>صورة بطاقة الهوية أو جواز السفر.</li><li>اجتياز اختبار اللغة أو المقابلة عند الحاجة.</li></ul>",
    admissionRequirementsEn:
      "<ul><li>High school certificate or equivalent.</li><li>Meeting the minimum admission score for the selected program.</li><li>National ID or passport copy.</li><li>Language test or interview when required.</li></ul>",
  };

  await db.delete(settingsTable);
  await insertSeed(settingsTable, values);
}

async function seedPageContent() {
  await db.delete(pageContentsTable);
  await insertSeed(pageContentsTable, [
    {
      pageKey: "about",
      titleAr: "من نحن",
      titleEn: "About Al-Noor",
      contentAr:
        "<h2>جامعة برؤية عالمية</h2><p>جامعة النور الدولية مؤسسة تعليمية حديثة تهدف إلى إعداد خريجين قادرين على المنافسة محليا وعالميا من خلال برامج أكاديمية مرتبطة بسوق العمل.</p><h2>رسالتنا</h2><p>تقديم تعليم تطبيقي عالي الجودة، وتشجيع البحث العلمي، وخدمة المجتمع من خلال شراكات فعالة.</p><h2>قيمنا</h2><ul><li>الجودة الأكاديمية</li><li>النزاهة والشفافية</li><li>الابتكار والمسؤولية المجتمعية</li></ul>",
      contentEn:
        "<h2>A university with a global vision</h2><p>Al-Noor International University is a modern institution preparing graduates who can compete locally and globally through market-aligned academic programs.</p><h2>Mission</h2><p>To provide high-quality applied education, encourage research, and serve the community through effective partnerships.</p><h2>Values</h2><ul><li>Academic quality</li><li>Integrity and transparency</li><li>Innovation and social responsibility</li></ul>",
      metaTitleAr: "من نحن | جامعة النور الدولية",
      metaTitleEn: "About | Al-Noor International University",
      metaDescriptionAr: "تعرف على رؤية ورسالة وقيم جامعة النور الدولية.",
      metaDescriptionEn: "Learn about the vision, mission, and values of Al-Noor International University.",
      status: "published",
      publishedAt: now,
    },
    {
      pageKey: "student-services",
      titleAr: "الخدمات الطلابية",
      titleEn: "Student Services",
      contentAr:
        "<h2>خدمات تدعم رحلة الطالب</h2><p>تقدم الجامعة منظومة خدمات متكاملة تشمل الدعم الأكاديمي، الإرشاد المهني، المكتبة الرقمية، الأنشطة الطلابية، وخدمات ذوي الهمم.</p><div><h3>الخدمات الرئيسية</h3><ul><li>المكتبة الرقمية وقواعد البيانات البحثية.</li><li>مركز الإرشاد الأكاديمي والنفسي.</li><li>مكتب التدريب والتوظيف.</li><li>بوابة الطلبات والشهادات الإلكترونية.</li></ul></div>",
      contentEn:
        "<h2>Services that support the student journey</h2><p>The university provides integrated services including academic support, career guidance, digital library access, student activities, and accessibility support.</p><div><h3>Main services</h3><ul><li>Digital library and research databases.</li><li>Academic and counseling center.</li><li>Internship and career office.</li><li>Online requests and certificates portal.</li></ul></div>",
      metaTitleAr: "الخدمات الطلابية | جامعة النور الدولية",
      metaTitleEn: "Student Services | Al-Noor International University",
      metaDescriptionAr: "خدمات الدعم الأكاديمي والمهني والرقمي المقدمة لطلاب جامعة النور الدولية.",
      metaDescriptionEn: "Academic, career, and digital support services for Al-Noor International University students.",
      status: "published",
      publishedAt: now,
    },
    {
      pageKey: "home",
      titleAr: "الرئيسية",
      titleEn: "Home",
      contentAr: "<p>الصفحة الرئيسية تعرض رسالة الجامعة وأهم الكليات والبرامج والأخبار.</p>",
      contentEn: "<p>The home page presents the university message, colleges, programs, and news.</p>",
      metaTitleAr: "جامعة النور الدولية | الرئيسية",
      metaTitleEn: "Al-Noor International University | Home",
      metaDescriptionAr: "بوابة جامعة النور الدولية للطلاب وأولياء الأمور والباحثين عن البرامج الأكاديمية.",
      metaDescriptionEn: "Al-Noor International University portal for students, parents, and academic program seekers.",
      status: "published",
      publishedAt: now,
    },
    {
      pageKey: "privacy",
      titleAr: "سياسة الخصوصية",
      titleEn: "Privacy Policy",
      contentAr:
        "<h2>حماية البيانات</h2><p>تحترم جامعة النور الدولية خصوصية زوار الموقع والطلاب والمتقدمين. نجمع البيانات اللازمة فقط لتقديم الخدمات الأكاديمية والإدارية.</p><h2>استخدام البيانات</h2><ul><li>معالجة طلبات القبول والتواصل مع المتقدمين.</li><li>تحسين تجربة الموقع والخدمات الرقمية.</li><li>الالتزام بالمتطلبات القانونية والتنظيمية.</li></ul><p>يمكنك طلب تحديث بياناتك أو حذفها عبر التواصل مع مكتب حماية البيانات.</p>",
      contentEn:
        "<h2>Data protection</h2><p>Al-Noor International University respects the privacy of website visitors, students, and applicants. We collect only the information needed to provide academic and administrative services.</p><h2>Data use</h2><ul><li>Processing admissions and applicant communication.</li><li>Improving the website and digital services.</li><li>Meeting legal and regulatory requirements.</li></ul><p>You may request updates or deletion of your data by contacting the data protection office.</p>",
      metaTitleAr: "سياسة الخصوصية | جامعة النور الدولية",
      metaTitleEn: "Privacy Policy | Al-Noor International University",
      metaDescriptionAr: "تعرف على كيفية حماية بياناتك واستخدامها في موقع جامعة النور الدولية.",
      metaDescriptionEn: "Learn how your data is protected and used on the Al-Noor International University website.",
      status: "published",
      publishedAt: now,
    },
    {
      pageKey: "tuition-fees",
      titleAr: "الرسوم الدراسية والمنح",
      titleEn: "Tuition Fees & Scholarships",
      contentAr:
        "<h2>نظرة عامة</h2><p>تختلف الرسوم حسب الكلية والبرنامج والمرحلة الأكاديمية. تعرض صفحة كل برنامج الرسوم التقريبية ويمكن تعديلها من لوحة التحكم.</p><table><thead><tr><th>الفئة</th><th>الرسوم السنوية التقريبية</th></tr></thead><tbody><tr><td>برامج العلوم الإنسانية</td><td>35,000 جنيه</td></tr><tr><td>برامج الحاسب والهندسة</td><td>55,000 جنيه</td></tr><tr><td>البرامج الصحية</td><td>75,000 جنيه</td></tr></tbody></table><h2>المنح</h2><p>تتوفر منح للتفوق الأكاديمي والأنشطة والاحتياجات الاجتماعية وفق ضوابط معلنة.</p>",
      contentEn:
        "<h2>Overview</h2><p>Fees vary by college, program, and academic level. Each program page shows estimated fees editable from the dashboard.</p><table><thead><tr><th>Category</th><th>Estimated annual fee</th></tr></thead><tbody><tr><td>Humanities programs</td><td>EGP 35,000</td></tr><tr><td>Computer and engineering programs</td><td>EGP 55,000</td></tr><tr><td>Health programs</td><td>EGP 75,000</td></tr></tbody></table><h2>Scholarships</h2><p>Scholarships are available for academic excellence, activities, and social support according to announced rules.</p>",
      metaTitleAr: "الرسوم الدراسية والمنح | جامعة النور الدولية",
      metaTitleEn: "Tuition Fees & Scholarships | Al-Noor International University",
      metaDescriptionAr: "معلومات الرسوم الدراسية وخيارات السداد والمنح في جامعة النور الدولية.",
      metaDescriptionEn: "Tuition, payment options, and scholarship information at Al-Noor International University.",
      status: "published",
      publishedAt: now,
    },
    {
      pageKey: "academic-calendar",
      titleAr: "التقويم الأكاديمي",
      titleEn: "Academic Calendar",
      contentAr:
        "<h2>العام الجامعي 2026/2027</h2><ul><li>فتح باب التقديم: 1 يونيو 2026</li><li>بداية الفصل الأول: 20 سبتمبر 2026</li><li>اختبارات منتصف الفصل: 15 نوفمبر 2026</li><li>اختبارات نهاية الفصل: 10 يناير 2027</li><li>بداية الفصل الثاني: 15 فبراير 2027</li></ul><p>يمكن تعديل هذه المواعيد من لوحة التحكم حسب التقويم الرسمي.</p>",
      contentEn:
        "<h2>Academic year 2026/2027</h2><ul><li>Applications open: June 1, 2026</li><li>Fall semester starts: September 20, 2026</li><li>Midterms: November 15, 2026</li><li>Final exams: January 10, 2027</li><li>Spring semester starts: February 15, 2027</li></ul><p>These dates can be edited from the dashboard according to the official calendar.</p>",
      metaTitleAr: "التقويم الأكاديمي | جامعة النور الدولية",
      metaTitleEn: "Academic Calendar | Al-Noor International University",
      metaDescriptionAr: "مواعيد التقديم والفصول الدراسية والاختبارات في جامعة النور الدولية.",
      metaDescriptionEn: "Application, semester, and exam dates at Al-Noor International University.",
      status: "published",
      publishedAt: now,
    },
    {
      pageKey: "centers",
      titleAr: "المراكز العلمية والتدريبية",
      titleEn: "Academic & Training Centers",
      contentAr:
        "<h2>مراكز الجامعة</h2><p>تعرض هذه الصفحة مراكز EUST في شكل قائمة قابلة للتصفح، وكل مركز له صفحة تفاصيل مستقلة قابلة للتعديل من لوحة التحكم.</p><ul><li><a href=\"/centers/political-economic-studies\">مركز العلوم والتكنولوجيا للدراسات السياسية والاقتصادية</a></li><li><a href=\"/centers/legal-administrative-studies\">مركز العلوم والتكنولوجيا للدراسات القانونية والإدارية</a></li><li><a href=\"/centers/arabic-language-teaching\">مركز تعليم اللغة العربية للناطقين بغيرها</a></li><li><a href=\"/centers/language-translation\">مركز اللغة والترجمة</a></li><li><a href=\"/centers/educational-rehabilitation\">مركز التأهيل التربوي</a></li><li><a href=\"/centers/international-arbitration\">مركز التحكيم الدولي</a></li><li><a href=\"/centers/sharia-studies\">مركز العلوم والتكنولوجيا للدراسات الشرعية</a></li></ul><h2>الخدمات</h2><p>تدعم المراكز التدريب المهني، الدراسات المتخصصة، التأهيل، الترجمة، التحكيم، وبرامج خدمة المجتمع.</p>",
      contentEn:
        "<h2>University Centers</h2><p>This page lists EUST centers as browsable entries. Each center has an editable detail page managed from the dashboard.</p><ul><li><a href=\"/centers/political-economic-studies\">Science and Technology Center for Political and Economic Studies</a></li><li><a href=\"/centers/legal-administrative-studies\">Science and Technology Center for Legal and Administrative Studies</a></li><li><a href=\"/centers/arabic-language-teaching\">Arabic Language Teaching Center for Non-Arabic Speakers</a></li><li><a href=\"/centers/language-translation\">Language and Translation Center</a></li><li><a href=\"/centers/educational-rehabilitation\">Educational Rehabilitation Center</a></li><li><a href=\"/centers/international-arbitration\">International Arbitration Center</a></li><li><a href=\"/centers/sharia-studies\">Science and Technology Center for Sharia Studies</a></li></ul><h2>Services</h2><p>The centers support professional training, specialist studies, qualification, translation, arbitration, and community service programs.</p>",
      metaTitleAr: "المراكز | الجامعة الأوروبية للعلوم والتكنولوجيا",
      metaTitleEn: "Centers | European University of Science and Technology",
      metaDescriptionAr: "المراكز العلمية والتدريبية في الجامعة الأوروبية للعلوم والتكنولوجيا.",
      metaDescriptionEn: "Academic and training centers at the European University of Science and Technology.",
      status: "published",
      publishedAt: now,
    },
    ...eustCenterPageContents,
    {
      pageKey: "journals",
      titleAr: "المجلات العلمية",
      titleEn: "Scientific Journals",
      contentAr:
        "<h2>مجلات EUST</h2><ul><li>المجلة الأوروبية للعلوم والتكنولوجيا للدراسات العربية والقانونية</li><li>المجلة الأوروبية للعلوم والتكنولوجيا للعلوم النفسية والتربوية</li><li>المجلة الأوروبية للعلوم والتكنولوجيا للدراسات القانونية والإدارية</li><li>المجلة الأوروبية للعلوم والتكنولوجيا للدراسات السياسية والاقتصادية</li></ul><p>يمكن من لوحة التحكم إضافة روابط أعداد المجلات، سياسات النشر، هيئة التحرير، وأرشيف الأبحاث.</p>",
      contentEn:
        "<h2>EUST Journals</h2><ul><li>European University Journal of Science and Technology for Arabic and Legal Studies</li><li>European University Journal of Science and Technology for Psychological and Educational Sciences</li><li>European University Journal of Science and Technology for Legal and Administrative Studies</li><li>European University Journal of Science and Technology for Political and Economic Studies</li></ul><p>The dashboard can later be used to add issue links, publication policies, editorial boards, and research archives.</p>",
      metaTitleAr: "المجلات العلمية | الجامعة الأوروبية للعلوم والتكنولوجيا",
      metaTitleEn: "Scientific Journals | European University of Science and Technology",
      metaDescriptionAr: "المجلات العلمية المنشورة ضمن بوابة الجامعة الأوروبية للعلوم والتكنولوجيا.",
      metaDescriptionEn: "Scientific journals listed for the European University of Science and Technology portal.",
      status: "published",
      publishedAt: now,
    },
    {
      pageKey: "memberships",
      titleAr: "الاعتمادات والعضويات",
      titleEn: "Memberships & Accreditations",
      contentAr:
        "<h2>مجالات الاعتماد</h2><ul><li>اعتماد المدربين</li><li>اعتماد المراكز</li><li>اعتماد الحقائب التدريبية</li></ul><p>هذه الصفحة مخصصة لعرض سياسات الاعتماد، المتطلبات، النماذج، وآلية التقديم بعد اعتمادها من إدارة الجامعة.</p>",
      contentEn:
        "<h2>Accreditation Areas</h2><ul><li>Accreditation of Trainers</li><li>Accreditation of Centers</li><li>Approval of Training Packages</li></ul><p>This page is prepared to publish accreditation policies, requirements, forms, and application workflow once approved by university administration.</p>",
      metaTitleAr: "الاعتمادات والعضويات | الجامعة الأوروبية للعلوم والتكنولوجيا",
      metaTitleEn: "Memberships & Accreditations | European University of Science and Technology",
      metaDescriptionAr: "اعتماد المدربين والمراكز والحقائب التدريبية في بوابة الجامعة.",
      metaDescriptionEn: "Trainer, center, and training package accreditation information.",
      status: "published",
      publishedAt: now,
    },
  ]);
}

async function seedAcademicData() {
  await db.delete(faqsTable);
  await db.delete(facultyTable);
  await db.delete(newsTable);
  await db.delete(programsTable);
  await db.delete(collegesTable);

  const colleges = await insertSeed(collegesTable, [
    {
      nameAr: "كلية الذكاء الاصطناعي",
      nameEn: "Faculty of Artificial Intelligence",
      slug: "faculty-of-artificial-intelligence",
      descriptionAr: "<p>كلية متخصصة في علوم الذكاء الاصطناعي، تعلم الآلة، الروبوتات، إنترنت الأشياء، علوم البيانات، وتطبيقات التحول الرقمي.</p>",
      descriptionEn: "<p>A faculty focused on artificial intelligence, machine learning, robotics, IoT, data science, and digital transformation applications.</p>",
      dean: "Dean of Artificial Intelligence",
      establishedYear: 2022,
      contactEmail: "ai@eust.uk",
      ...collegeAcademicProfile,
      ...eustCollegeProfiles.ai,
      metaTitleAr: "كلية الذكاء الاصطناعي | EUST",
      metaTitleEn: "Faculty of Artificial Intelligence | EUST",
      metaDescriptionAr: "برامج الذكاء الاصطناعي والروبوتات وعلوم البيانات في الجامعة الأوروبية للعلوم والتكنولوجيا.",
      metaDescriptionEn: "Artificial intelligence, robotics, and data science programs at the European University of Science and Technology.",
      status: "published",
    },
    {
      nameAr: "كلية الدراسات الإسلامية",
      nameEn: "College of Islamic Studies",
      slug: "college-of-islamic-studies",
      descriptionAr: "<p>كلية تقدم مسارات أكاديمية في الدراسات الإسلامية واللغة العربية للناطقين بغيرها، مع ربط الدراسة بالبحث والتعليم والحوار الثقافي.</p>",
      descriptionEn: "<p>A college offering academic pathways in Islamic Studies and Arabic for non-native speakers, connecting study with research, teaching, and intercultural communication.</p>",
      dean: "Dean of Islamic Studies",
      establishedYear: 2022,
      contactEmail: "islamic.studies@eust.uk",
      ...collegeAcademicProfile,
      ...eustCollegeProfiles.islamic,
      status: "published",
    },
    {
      nameAr: "كلية إدارة الأعمال",
      nameEn: "College of Business Administration at EUST",
      slug: "business-administration",
      descriptionAr: "<p>كلية تركز على الإدارة، ريادة الأعمال، التسويق، المحاسبة، التمويل، والمهارات القيادية المطلوبة في بيئات الأعمال الحديثة.</p>",
      descriptionEn: "<p>A college focused on management, entrepreneurship, marketing, accounting, finance, and leadership skills for modern business environments.</p>",
      dean: "Dean of Business Administration",
      establishedYear: 2022,
      contactEmail: "business@eust.uk",
      ...collegeAcademicProfile,
      ...eustCollegeProfiles.business,
      status: "published",
    },
    {
      nameAr: "كلية التمريض",
      nameEn: "Faculty of Nursing",
      slug: "faculty-of-nursing",
      descriptionAr: "<p>كلية تعنى بإعداد كوادر تمريضية قادرة على تقديم رعاية آمنة، إنسانية، ومبنية على الدليل العلمي.</p>",
      descriptionEn: "<p>A faculty preparing nursing professionals to deliver safe, compassionate, evidence-based care.</p>",
      dean: "Dean of Nursing",
      establishedYear: 2022,
      contactEmail: "nursing@eust.uk",
      ...collegeAcademicProfile,
      ...eustCollegeProfiles.nursing,
      status: "published",
    },
    {
      nameAr: "كلية اللغات والترجمة",
      nameEn: "College of Languages and Interpretation",
      slug: "college-of-languages-and-interpretation",
      descriptionAr: "<p>كلية متخصصة في اللغات، الترجمة التحريرية، الترجمة الفورية، التواصل الثقافي، وخدمات اللغة للأعمال والمؤسسات.</p>",
      descriptionEn: "<p>A college specializing in languages, translation, interpretation, intercultural communication, and language services for business and institutions.</p>",
      dean: "Dean of Languages and Interpretation",
      establishedYear: 2022,
      contactEmail: "languages@eust.uk",
      ...collegeAcademicProfile,
      ...eustCollegeProfiles.languages,
      status: "published",
    },
    {
      nameAr: "كلية الحاسب وعلوم المعلومات",
      nameEn: "Faculty of Computer and Information Sciences",
      slug: "faculty-of-computer-information-sciences",
      descriptionAr: "<p>كلية تركز على علوم الحاسب، نظم المعلومات، هندسة البرمجيات، الشبكات، قواعد البيانات، وأمن المعلومات.</p>",
      descriptionEn: "<p>A faculty focused on computer science, information systems, software engineering, networks, databases, and information security.</p>",
      dean: "Dean of Computer and Information Sciences",
      establishedYear: 2022,
      contactEmail: "computing@eust.uk",
      ...collegeAcademicProfile,
      departmentsAr: "<ul><li>علوم الحاسب.</li><li>نظم المعلومات.</li><li>هندسة البرمجيات.</li><li>الشبكات وأمن المعلومات.</li></ul>",
      departmentsEn: "<ul><li>Computer Science.</li><li>Information Systems.</li><li>Software Engineering.</li><li>Networks and Information Security.</li></ul>",
      visionAr: "<p>إعداد متخصصين في الحوسبة ونظم المعلومات قادرين على تطوير حلول رقمية آمنة وفعالة.</p>",
      visionEn: "<p>To prepare computing and information systems specialists capable of developing secure and effective digital solutions.</p>",
      status: "published",
    },
    {
      nameAr: "كلية العلوم والفيزياء",
      nameEn: "Faculty of Science and Physics",
      slug: "faculty-of-science-and-physics",
      descriptionAr: "<p>كلية تهتم بالعلوم الأساسية والتطبيقية، الفيزياء، البحث العلمي، والتحليل المعملي الداعم للتخصصات التقنية والصحية.</p>",
      descriptionEn: "<p>A faculty concerned with basic and applied sciences, physics, scientific research, and laboratory analysis supporting technical and health disciplines.</p>",
      dean: "Dean of Science and Physics",
      establishedYear: 2022,
      contactEmail: "science.physics@eust.uk",
      ...collegeAcademicProfile,
      departmentsAr: "<ul><li>الفيزياء العامة.</li><li>العلوم التطبيقية.</li><li>المعامل والقياسات.</li><li>البحث العلمي.</li></ul>",
      departmentsEn: "<ul><li>General Physics.</li><li>Applied Sciences.</li><li>Laboratories and Measurements.</li><li>Scientific Research.</li></ul>",
      visionAr: "<p>تقديم تعليم علمي وبحث تطبيقي يخدم التكنولوجيا والصحة والصناعة.</p>",
      visionEn: "<p>To provide scientific education and applied research serving technology, health, and industry.</p>",
      status: "published",
    },
    {
      nameAr: "كلية طب الأسنان",
      nameEn: "Faculty of Dentistry",
      slug: "faculty-of-dentistry",
      descriptionAr: "<p>كلية تؤهل الطلاب لأساسيات طب الأسنان، صحة الفم، المهارات السريرية، وأخلاقيات الرعاية الصحية.</p>",
      descriptionEn: "<p>A faculty preparing students in dental fundamentals, oral health, clinical skills, and healthcare ethics.</p>",
      dean: "Dean of Dentistry",
      establishedYear: 2022,
      contactEmail: "dentistry@eust.uk",
      ...collegeAcademicProfile,
      departmentsAr: "<ul><li>علوم الفم والأسنان الأساسية.</li><li>طب الأسنان الوقائي.</li><li>المحاكاة السريرية.</li><li>صحة الفم المجتمعية.</li></ul>",
      departmentsEn: "<ul><li>Basic Oral and Dental Sciences.</li><li>Preventive Dentistry.</li><li>Clinical Simulation.</li><li>Community Oral Health.</li></ul>",
      visionAr: "<p>إعداد خريجين قادرين على تقديم رعاية فموية آمنة ومبنية على الدليل.</p>",
      visionEn: "<p>To prepare graduates capable of delivering safe, evidence-based oral healthcare.</p>",
      status: "published",
    },
    {
      nameAr: "كلية القانون والدراسات القانونية",
      nameEn: "Faculty of Law and Legal Studies",
      slug: "faculty-of-law-legal-studies",
      descriptionAr: "<p>كلية تقدم مسارات في القانون، الدراسات القانونية، التحكيم، الحوكمة، والصياغة القانونية.</p>",
      descriptionEn: "<p>A faculty offering pathways in law, legal studies, arbitration, governance, and legal drafting.</p>",
      dean: "Dean of Law and Legal Studies",
      establishedYear: 2022,
      contactEmail: "law@eust.uk",
      ...collegeAcademicProfile,
      departmentsAr: "<ul><li>القانون العام.</li><li>القانون الخاص.</li><li>القانون الدولي والتحكيم.</li><li>الدراسات القانونية والإدارية.</li></ul>",
      departmentsEn: "<ul><li>Public Law.</li><li>Private Law.</li><li>International Law and Arbitration.</li><li>Legal and Administrative Studies.</li></ul>",
      visionAr: "<p>تأهيل دارسين قادرين على فهم النظم القانونية وتحليل القضايا وصياغة الحلول.</p>",
      visionEn: "<p>To prepare learners able to understand legal systems, analyze cases, and draft solutions.</p>",
      status: "published",
    },
    {
      nameAr: "كلية الطب",
      nameEn: "Faculty of Medicine",
      slug: "faculty-of-medicine",
      descriptionAr: "<p>كلية تعنى بأساسيات العلوم الطبية، أخلاقيات الممارسة، البحث الصحي، والتدريب السريري المتدرج.</p>",
      descriptionEn: "<p>A faculty concerned with medical sciences, practice ethics, health research, and progressive clinical training.</p>",
      dean: "Dean of Medicine",
      establishedYear: 2022,
      contactEmail: "medicine@eust.uk",
      ...collegeAcademicProfile,
      departmentsAr: "<ul><li>العلوم الطبية الأساسية.</li><li>الصحة العامة.</li><li>المهارات السريرية.</li><li>البحث الطبي.</li></ul>",
      departmentsEn: "<ul><li>Basic Medical Sciences.</li><li>Public Health.</li><li>Clinical Skills.</li><li>Medical Research.</li></ul>",
      visionAr: "<p>إعداد أطباء وباحثين صحيين ملتزمين بالرعاية الآمنة والبحث والأخلاقيات.</p>",
      visionEn: "<p>To prepare physicians and health researchers committed to safe care, research, and ethics.</p>",
      status: "published",
    },
    {
      nameAr: "كلية الصيدلة",
      nameEn: "Faculty of Pharmacy",
      slug: "faculty-of-pharmacy",
      descriptionAr: "<p>كلية تؤهل الطلاب في علوم الدواء، الرعاية الصيدلية، التصنيع، الجودة، وسلامة استخدام الأدوية.</p>",
      descriptionEn: "<p>A faculty preparing students in pharmaceutical sciences, pharmacy care, manufacturing, quality, and medication safety.</p>",
      dean: "Dean of Pharmacy",
      establishedYear: 2022,
      contactEmail: "pharmacy@eust.uk",
      ...collegeAcademicProfile,
      departmentsAr: "<ul><li>الكيمياء الصيدلية.</li><li>الصيدلانيات.</li><li>العقاقير.</li><li>الرعاية الصيدلية.</li></ul>",
      departmentsEn: "<ul><li>Pharmaceutical Chemistry.</li><li>Pharmaceutics.</li><li>Pharmacognosy.</li><li>Pharmacy Care.</li></ul>",
      visionAr: "<p>إعداد كوادر صيدلية قادرة على دعم الرعاية الصحية والصناعة الدوائية.</p>",
      visionEn: "<p>To prepare pharmacy professionals able to support healthcare and pharmaceutical industry.</p>",
      status: "published",
    },
    {
      nameAr: "كلية العلاج الطبيعي",
      nameEn: "Faculty of Physiotherapy",
      slug: "faculty-of-physiotherapy",
      descriptionAr: "<p>كلية تركز على التأهيل الحركي، العلاج الطبيعي، علوم الحركة، وبرامج تحسين جودة الحياة.</p>",
      descriptionEn: "<p>A faculty focused on rehabilitation, physiotherapy, movement sciences, and quality-of-life improvement programs.</p>",
      dean: "Dean of Physiotherapy",
      establishedYear: 2022,
      contactEmail: "physiotherapy@eust.uk",
      ...collegeAcademicProfile,
      departmentsAr: "<ul><li>العلاج الطبيعي للحالات العضلية والعصبية.</li><li>علوم الحركة.</li><li>التأهيل الرياضي.</li><li>التأهيل المجتمعي.</li></ul>",
      departmentsEn: "<ul><li>Musculoskeletal and Neurological Physiotherapy.</li><li>Movement Sciences.</li><li>Sports Rehabilitation.</li><li>Community Rehabilitation.</li></ul>",
      visionAr: "<p>تأهيل ممارسين قادرين على تقديم خطط علاجية مبنية على التقييم والدليل العلمي.</p>",
      visionEn: "<p>To qualify practitioners able to provide treatment plans based on assessment and evidence.</p>",
      status: "published",
    },
    {
      nameAr: "كلية القراءات",
      nameEn: "Faculty of Readings",
      slug: "faculty-of-readings",
      descriptionAr: "<p>كلية متخصصة في القراءات وعلوم القرآن، الضبط، الأداء، البحث، وخدمة الدراسات القرآنية.</p>",
      descriptionEn: "<p>A faculty specializing in Quranic readings, Quranic sciences, recitation accuracy, performance, research, and Quranic studies service.</p>",
      dean: "Dean of Readings",
      establishedYear: 2022,
      contactEmail: "readings@eust.uk",
      ...collegeAcademicProfile,
      departmentsAr: "<ul><li>القراءات.</li><li>علوم القرآن.</li><li>الرسم والضبط.</li><li>البحث والتحقيق.</li></ul>",
      departmentsEn: "<ul><li>Quranic Readings.</li><li>Quranic Sciences.</li><li>Orthography and Accuracy.</li><li>Research and Textual Scholarship.</li></ul>",
      visionAr: "<p>خدمة علوم القرآن والقراءات بإعداد متخصصين يجمعون بين الأداء العلمي والبحث الأكاديمي.</p>",
      visionEn: "<p>To serve Quranic sciences and readings by preparing specialists combining scholarly performance and academic research.</p>",
      status: "published",
    },
  ]).returning();

  const ai = colleges[0];
  const islamic = colleges[1];
  const business = colleges[2];
  const nursing = colleges[3];
  const languages = colleges[4];
  const computing = colleges[5];
  const science = colleges[6];
  const dentistry = colleges[7];
  const law = colleges[8];
  const medicine = colleges[9];
  const pharmacy = colleges[10];
  const physiotherapy = colleges[11];
  const readings = colleges[12];

  await insertSeed(programsTable, [
    {
      collegeId: ai.id,
      nameAr: "بكالوريوس الذكاء الاصطناعي",
      nameEn: "BSc Artificial Intelligence",
      slug: "bsc-artificial-intelligence",
      level: "bachelor",
      durationYears: 4,
      tuitionFees: 55000,
      currency: "EGP",
      programCode: "EUST-AI-BSC",
      coordinatorName: "AI Program Coordinator",
      coordinatorEmail: "ai.program@eust.uk",
      ...programAcademicProfile,
      descriptionAr: "<p>برنامج يمنح الطالب أساسا قويا في الذكاء الاصطناعي، البرمجة، تعلم الآلة، الروبوتات، الأنظمة المدمجة، وعلوم البيانات.</p>",
      descriptionEn: "<p>A program giving students a strong foundation in artificial intelligence, programming, machine learning, robotics, embedded systems, and data science.</p>",
      admissionRequirementsAr: "<ul><li>الثانوية العامة شعبة علمي رياضة أو ما يعادلها.</li><li>اجتياز اختبار القدرات التقنية.</li></ul>",
      admissionRequirementsEn: "<ul><li>STEM high school track or equivalent.</li><li>Passing the technical aptitude test.</li></ul>",
      careerOpportunitiesAr: "<ul><li>مهندس ذكاء اصطناعي</li><li>محلل بيانات</li><li>مطوّر حلول روبوتية</li><li>مهندس تعلم آلة</li></ul>",
      careerOpportunitiesEn: "<ul><li>AI Engineer</li><li>Data Analyst</li><li>Robotics Solutions Developer</li><li>Machine Learning Engineer</li></ul>",
      status: "published",
    },
    {
      collegeId: ai.id,
      nameAr: "برنامج الذكاء الاصطناعي الحيوي",
      nameEn: "Bio-Artificial Intelligence Program",
      slug: "bio-artificial-intelligence",
      level: "bachelor",
      durationYears: 4,
      tuitionFees: 62000,
      currency: "EGP",
      programCode: "EUST-BIOAI-BSC",
      coordinatorName: "Bio-AI Program Coordinator",
      coordinatorEmail: "bioai@eust.uk",
      ...programAcademicProfile,
      descriptionAr: "<p>مسار تطبيقي يربط الذكاء الاصطناعي بتطبيقات الصحة، المختبرات، البيانات الحيوية، والأنظمة الذكية في القطاع الطبي.</p>",
      descriptionEn: "<p>An applied pathway connecting artificial intelligence with healthcare applications, laboratories, bio-data, and intelligent medical systems.</p>",
      status: "published",
    },
    {
      collegeId: islamic.id,
      nameAr: "بكالوريوس الدراسات الإسلامية",
      nameEn: "Bachelor's Degree in Islamic Studies",
      slug: "bachelor-islamic-studies",
      level: "bachelor",
      durationYears: 4,
      tuitionFees: 35000,
      currency: "EGP",
      programCode: "EUST-IS-BSC",
      coordinatorName: "Islamic Studies Coordinator",
      coordinatorEmail: "islamic.program@eust.uk",
      ...programAcademicProfile,
      descriptionAr: "<p>برنامج أكاديمي في علوم الشريعة، القرآن، التاريخ الإسلامي، الثقافة العربية، ومهارات البحث الشرعي للطلاب المحليين والدوليين.</p>",
      descriptionEn: "<p>An academic program in Sharia sciences, Quranic studies, Islamic history, Arabic culture, and scholarly research skills for local and international learners.</p>",
      status: "published",
    },
    {
      collegeId: business.id,
      nameAr: "بكالوريوس إدارة الأعمال",
      nameEn: "BBA Business Administration",
      slug: "business-administration",
      level: "bachelor",
      durationYears: 4,
      tuitionFees: 42000,
      currency: "EGP",
      programCode: "BUS-BBA",
      coordinatorName: "Business Program Coordinator",
      coordinatorEmail: "business.program@eust.uk",
      ...programAcademicProfile,
      descriptionAr: "<p>برنامج في إدارة الأعمال يركز على الإدارة، التسويق، المحاسبة، التمويل، ريادة الأعمال، واتخاذ القرار في المؤسسات.</p>",
      descriptionEn: "<p>A business administration program focused on management, marketing, accounting, finance, entrepreneurship, and organizational decision-making.</p>",
      status: "published",
    },
    {
      collegeId: nursing.id,
      nameAr: "بكالوريوس التمريض",
      nameEn: "BSc Nursing",
      slug: "bsc-nursing",
      level: "bachelor",
      durationYears: 4,
      tuitionFees: 68000,
      currency: "EGP",
      programCode: "EUST-NUR-BSC",
      coordinatorName: "Nursing Program Coordinator",
      coordinatorEmail: "nursing.program@eust.uk",
      ...programAcademicProfile,
      descriptionAr: "<p>برنامج يؤهل الطالب لممارسة التمريض المهني، الرعاية السريرية، التواصل مع المرضى، والعمل ضمن فرق صحية متعددة التخصصات.</p>",
      descriptionEn: "<p>A program preparing students for professional nursing practice, clinical care, patient communication, and interprofessional healthcare teamwork.</p>",
      status: "published",
    },
    {
      collegeId: islamic.id,
      nameAr: "ماجستير علوم القرآن",
      nameEn: "Master's Degree in Quranic Sciences",
      slug: "master-quranic-sciences",
      level: "master",
      durationYears: 2,
      tuitionFees: 42000,
      currency: "EGP",
      programCode: "EUST-QUR-MSC",
      coordinatorName: "Quranic Sciences Coordinator",
      coordinatorEmail: "quranic.sciences@eust.uk",
      ...programAcademicProfile,
      degreeAwardedAr: "درجة الماجستير",
      degreeAwardedEn: "Master's Degree",
      descriptionAr: "<p>برنامج دراسات عليا في علوم القرآن، مناهج التفسير، البحث العلمي، وتطبيقات الدراسات القرآنية في التعليم والمجتمع.</p>",
      descriptionEn: "<p>A graduate program in Quranic sciences, interpretation methodologies, research methods, and applications of Quranic studies in education and society.</p>",
      status: "published",
    },
    {
      collegeId: islamic.id,
      nameAr: "ماجستير المصارف الإسلامية",
      nameEn: "Master's Degree in Islamic Banking",
      slug: "master-islamic-banking",
      level: "master",
      durationYears: 2,
      tuitionFees: 44000,
      currency: "EGP",
      programCode: "EUST-IBF-MSC",
      coordinatorName: "Islamic Banking Coordinator",
      coordinatorEmail: "islamic.banking@eust.uk",
      ...programAcademicProfile,
      degreeAwardedAr: "درجة الماجستير",
      degreeAwardedEn: "Master's Degree",
      descriptionAr: "<p>برنامج يربط فقه المعاملات بالتمويل الحديث، إدارة المخاطر، المنتجات المصرفية الإسلامية، والحوكمة الشرعية.</p>",
      descriptionEn: "<p>A program linking Islamic commercial jurisprudence with modern finance, risk management, Islamic banking products, and Sharia governance.</p>",
      status: "published",
    },
    {
      collegeId: islamic.id,
      nameAr: "دكتوراه التاريخ الإسلامي",
      nameEn: "PhD in Islamic History",
      slug: "phd-islamic-history",
      level: "phd",
      durationYears: 3,
      tuitionFees: 52000,
      currency: "EGP",
      programCode: "EUST-IH-PHD",
      coordinatorName: "Islamic History Coordinator",
      coordinatorEmail: "islamic.history@eust.uk",
      ...programAcademicProfile,
      degreeAwardedAr: "درجة الدكتوراه",
      degreeAwardedEn: "Doctor of Philosophy",
      descriptionAr: "<p>برنامج بحثي متقدم في التاريخ والحضارة الإسلامية، مناهج التحقيق، المصادر، والتحليل التاريخي المقارن.</p>",
      descriptionEn: "<p>An advanced research program in Islamic history and civilization, source criticism, manuscript methods, and comparative historical analysis.</p>",
      status: "published",
    },
    {
      collegeId: languages.id,
      nameAr: "بكالوريوس اللغات والترجمة",
      nameEn: "BA Languages and Translation",
      slug: "ba-languages-translation",
      level: "bachelor",
      durationYears: 4,
      tuitionFees: 38000,
      currency: "EGP",
      programCode: "EUST-LTR-BA",
      coordinatorName: "Languages Program Coordinator",
      coordinatorEmail: "languages.program@eust.uk",
      ...programAcademicProfile,
      degreeAwardedAr: "درجة البكالوريوس",
      degreeAwardedEn: "Bachelor Degree",
      descriptionAr: "<p>برنامج يؤهل الطلاب للترجمة التحريرية والفورية، التواصل متعدد الثقافات، التحرير اللغوي، وخدمات اللغة في المؤسسات.</p>",
      descriptionEn: "<p>A program preparing students for translation, interpretation, intercultural communication, language editing, and institutional language services.</p>",
      careerOpportunitiesAr: "<ul><li>مترجم تحريري</li><li>مترجم فوري</li><li>محرر لغوي</li><li>منسق تواصل دولي</li></ul>",
      careerOpportunitiesEn: "<ul><li>Translator</li><li>Interpreter</li><li>Language Editor</li><li>International Communication Coordinator</li></ul>",
      status: "published",
    },
    {
      collegeId: ai.id,
      nameAr: "ماجستير الذكاء الاصطناعي",
      nameEn: "Master's Degree in Artificial Intelligence",
      slug: "master-artificial-intelligence",
      level: "master",
      durationYears: 2,
      tuitionFees: 65000,
      currency: "EGP",
      programCode: "EUST-AI-MSC",
      coordinatorName: "AI Graduate Coordinator",
      coordinatorEmail: "ai.graduate@eust.uk",
      ...programAcademicProfile,
      degreeAwardedAr: "درجة الماجستير",
      degreeAwardedEn: "Master's Degree",
      descriptionAr: "<p>برنامج دراسات عليا في تعلم الآلة، التعلم العميق، معالجة البيانات، أنظمة القرار، وأبحاث الذكاء الاصطناعي التطبيقية.</p>",
      descriptionEn: "<p>A graduate program in machine learning, deep learning, data processing, decision systems, and applied AI research.</p>",
      curriculumAr: "<ol><li>منهجيات البحث في الذكاء الاصطناعي.</li><li>تعلم آلة متقدم وتعلم عميق.</li><li>بيانات ضخمة ونظم قرار.</li><li>رسالة أو مشروع تطبيقي.</li></ol>",
      curriculumEn: "<ol><li>AI research methodologies.</li><li>Advanced machine learning and deep learning.</li><li>Big data and decision systems.</li><li>Thesis or applied project.</li></ol>",
      status: "published",
    },
    {
      collegeId: ai.id,
      nameAr: "دكتوراه الذكاء الاصطناعي",
      nameEn: "PhD in Artificial Intelligence",
      slug: "phd-artificial-intelligence",
      level: "phd",
      durationYears: 3,
      tuitionFees: 76000,
      currency: "EGP",
      programCode: "EUST-AI-PHD",
      coordinatorName: "AI Research Coordinator",
      coordinatorEmail: "ai.research@eust.uk",
      ...programAcademicProfile,
      degreeAwardedAr: "درجة الدكتوراه",
      degreeAwardedEn: "Doctor of Philosophy",
      descriptionAr: "<p>برنامج بحثي متقدم لإنتاج أبحاث أصلية في الذكاء الاصطناعي، الروبوتات، علوم البيانات، والتحول الرقمي.</p>",
      descriptionEn: "<p>An advanced research program for original scholarship in AI, robotics, data science, and digital transformation.</p>",
      graduationRequirementsAr: "<ul><li>خطة بحث معتمدة.</li><li>نشر أو قبول بحث علمي وفق ضوابط البرنامج.</li><li>مناقشة الرسالة أمام لجنة علمية.</li></ul>",
      graduationRequirementsEn: "<ul><li>Approved research proposal.</li><li>Published or accepted research according to program rules.</li><li>Defense before an academic committee.</li></ul>",
      status: "published",
    },
    {
      collegeId: islamic.id,
      nameAr: "ماجستير الفقه وأصوله",
      nameEn: "Master's Degree in Jurisprudence and Fundamentals",
      slug: "master-jurisprudence-fundamentals",
      level: "master",
      durationYears: 2,
      tuitionFees: 43000,
      currency: "EGP",
      programCode: "EUST-FIQH-MSC",
      coordinatorName: "Fiqh Program Coordinator",
      coordinatorEmail: "fiqh@eust.uk",
      ...programAcademicProfile,
      degreeAwardedAr: "درجة الماجستير",
      degreeAwardedEn: "Master's Degree",
      descriptionAr: "<p>برنامج متخصص في الفقه، أصوله، مناهج الاستدلال، القضايا المعاصرة، ومهارات البحث الشرعي.</p>",
      descriptionEn: "<p>A specialized program in jurisprudence, fundamentals, methods of reasoning, contemporary issues, and Sharia research skills.</p>",
      status: "published",
    },
    {
      collegeId: islamic.id,
      nameAr: "دكتوراه الفقه وأصوله",
      nameEn: "PhD in Jurisprudence and Fundamentals",
      slug: "phd-jurisprudence-fundamentals",
      level: "phd",
      durationYears: 3,
      tuitionFees: 53000,
      currency: "EGP",
      programCode: "EUST-FIQH-PHD",
      coordinatorName: "Fiqh Research Coordinator",
      coordinatorEmail: "fiqh.research@eust.uk",
      ...programAcademicProfile,
      degreeAwardedAr: "درجة الدكتوراه",
      degreeAwardedEn: "Doctor of Philosophy",
      descriptionAr: "<p>مسار بحثي لإعداد دراسات أصلية في الفقه وأصوله، تحقيق النصوص، والقضايا الشرعية المعاصرة.</p>",
      descriptionEn: "<p>A research pathway for original studies in jurisprudence, fundamentals, textual scholarship, and contemporary Sharia issues.</p>",
      status: "published",
    },
    {
      collegeId: business.id,
      nameAr: "ماجستير إدارة الأعمال",
      nameEn: "Master of Business Administration",
      slug: "master-business-administration",
      level: "master",
      durationYears: 2,
      tuitionFees: 52000,
      currency: "EGP",
      programCode: "EUST-MBA",
      coordinatorName: "MBA Coordinator",
      coordinatorEmail: "mba@eust.uk",
      ...programAcademicProfile,
      degreeAwardedAr: "درجة الماجستير",
      degreeAwardedEn: "Master's Degree",
      descriptionAr: "<p>برنامج مهني في القيادة، الاستراتيجية، التمويل، التسويق، ريادة الأعمال، وإدارة التحول الرقمي.</p>",
      descriptionEn: "<p>A professional program in leadership, strategy, finance, marketing, entrepreneurship, and digital transformation management.</p>",
      careerOpportunitiesAr: "<ul><li>مدير عمليات</li><li>استشاري أعمال</li><li>مدير تسويق</li><li>رائد أعمال</li></ul>",
      careerOpportunitiesEn: "<ul><li>Operations Manager</li><li>Business Consultant</li><li>Marketing Manager</li><li>Entrepreneur</li></ul>",
      status: "published",
    },
    {
      collegeId: nursing.id,
      nameAr: "دبلوم التأهيل التمريضي",
      nameEn: "Diploma in Nursing Practice",
      slug: "diploma-nursing-practice",
      level: "diploma",
      durationYears: 1,
      tuitionFees: 30000,
      currency: "EGP",
      programCode: "EUST-NUR-DIP",
      coordinatorName: "Nursing Diploma Coordinator",
      coordinatorEmail: "nursing.diploma@eust.uk",
      ...programAcademicProfile,
      degreeAwardedAr: "دبلوم مهني",
      degreeAwardedEn: "Professional Diploma",
      descriptionAr: "<p>دبلوم تطبيقي يركز على مهارات الرعاية الأساسية، سلامة المرضى، مكافحة العدوى، والتواصل في بيئة الرعاية الصحية.</p>",
      descriptionEn: "<p>An applied diploma focused on core care skills, patient safety, infection control, and communication in healthcare settings.</p>",
      status: "published",
    },
    {
      collegeId: languages.id,
      nameAr: "ماجستير الترجمة الفورية والتحريرية",
      nameEn: "Master's Degree in Translation and Interpretation",
      slug: "master-translation-interpretation",
      level: "master",
      durationYears: 2,
      tuitionFees: 45000,
      currency: "EGP",
      programCode: "EUST-TI-MA",
      coordinatorName: "Translation Graduate Coordinator",
      coordinatorEmail: "translation@eust.uk",
      ...programAcademicProfile,
      degreeAwardedAr: "درجة الماجستير",
      degreeAwardedEn: "Master's Degree",
      descriptionAr: "<p>برنامج متقدم في الترجمة المتخصصة، الترجمة الفورية، أدوات الترجمة، التحرير، وإدارة مشروعات اللغة.</p>",
      descriptionEn: "<p>An advanced program in specialized translation, interpretation, translation technologies, editing, and language project management.</p>",
      status: "published",
    },
    {
      collegeId: computing.id,
      nameAr: "بكالوريوس علوم الحاسب",
      nameEn: "BSc Computer Science",
      slug: "bsc-computer-science",
      level: "bachelor",
      durationYears: 4,
      tuitionFees: 56000,
      currency: "EGP",
      programCode: "EUST-CS-BSC",
      coordinatorName: "Computer Science Coordinator",
      coordinatorEmail: "computer.science@eust.uk",
      ...programAcademicProfile,
      descriptionAr: "<p>برنامج يركز على البرمجة، الخوارزميات، قواعد البيانات، نظم التشغيل، الشبكات، وأمن المعلومات.</p>",
      descriptionEn: "<p>A program focused on programming, algorithms, databases, operating systems, networks, and information security.</p>",
      careerOpportunitiesAr: "<ul><li>مطوّر برمجيات</li><li>مهندس نظم</li><li>محلل بيانات</li><li>مختص أمن معلومات</li></ul>",
      careerOpportunitiesEn: "<ul><li>Software Developer</li><li>Systems Engineer</li><li>Data Analyst</li><li>Information Security Specialist</li></ul>",
      status: "published",
    },
    {
      collegeId: science.id,
      nameAr: "بكالوريوس العلوم والفيزياء",
      nameEn: "BSc Science and Physics",
      slug: "bsc-science-physics",
      level: "bachelor",
      durationYears: 4,
      tuitionFees: 41000,
      currency: "EGP",
      programCode: "EUST-PHY-BSC",
      coordinatorName: "Science and Physics Coordinator",
      coordinatorEmail: "physics@eust.uk",
      ...programAcademicProfile,
      descriptionAr: "<p>برنامج في الفيزياء والعلوم التطبيقية يدمج الأساس النظري بالتجارب المعملية والبحث العلمي.</p>",
      descriptionEn: "<p>A physics and applied science program combining theoretical foundations, laboratory experiments, and scientific research.</p>",
      status: "published",
    },
    {
      collegeId: dentistry.id,
      nameAr: "بكالوريوس طب الأسنان",
      nameEn: "BDS Dentistry",
      slug: "bds-dentistry",
      level: "bachelor",
      durationYears: 5,
      tuitionFees: 92000,
      currency: "EGP",
      programCode: "EUST-DEN-BDS",
      coordinatorName: "Dentistry Program Coordinator",
      coordinatorEmail: "dentistry.program@eust.uk",
      ...programAcademicProfile,
      degreeAwardedAr: "بكالوريوس طب وجراحة الفم والأسنان",
      degreeAwardedEn: "Bachelor of Dental Surgery",
      descriptionAr: "<p>برنامج يؤهل الطلاب في علوم الفم والأسنان، المهارات السريرية، الوقاية، وأخلاقيات الرعاية الصحية.</p>",
      descriptionEn: "<p>A program preparing students in oral and dental sciences, clinical skills, prevention, and healthcare ethics.</p>",
      internshipAr: "<p>يتضمن تدريبا معمليا وسريريا تدريجيا ومحاكاة قبل التدريب الميداني.</p>",
      internshipEn: "<p>Includes progressive laboratory and clinical simulation training before field practice.</p>",
      status: "published",
    },
    {
      collegeId: law.id,
      nameAr: "بكالوريوس القانون والدراسات القانونية",
      nameEn: "LLB Law and Legal Studies",
      slug: "llb-law-legal-studies",
      level: "bachelor",
      durationYears: 4,
      tuitionFees: 38000,
      currency: "EGP",
      programCode: "EUST-LAW-LLB",
      coordinatorName: "Law Program Coordinator",
      coordinatorEmail: "law.program@eust.uk",
      ...programAcademicProfile,
      descriptionAr: "<p>برنامج في القانون والدراسات القانونية يركز على التشريعات، التحليل القانوني، الصياغة، التحكيم، والحوكمة.</p>",
      descriptionEn: "<p>A law and legal studies program focused on legislation, legal analysis, drafting, arbitration, and governance.</p>",
      careerOpportunitiesAr: "<ul><li>باحث قانوني</li><li>مستشار قانوني مساعد</li><li>منسق عقود</li><li>مختص حوكمة وامتثال</li></ul>",
      careerOpportunitiesEn: "<ul><li>Legal Researcher</li><li>Assistant Legal Consultant</li><li>Contracts Coordinator</li><li>Governance and Compliance Specialist</li></ul>",
      status: "published",
    },
    {
      collegeId: medicine.id,
      nameAr: "بكالوريوس الطب والجراحة",
      nameEn: "Bachelor of Medicine and Surgery",
      slug: "mbbs-medicine-surgery",
      level: "bachelor",
      durationYears: 6,
      tuitionFees: 110000,
      currency: "EGP",
      programCode: "EUST-MED-MBBS",
      coordinatorName: "Medicine Program Coordinator",
      coordinatorEmail: "medicine.program@eust.uk",
      ...programAcademicProfile,
      degreeAwardedAr: "بكالوريوس الطب والجراحة",
      degreeAwardedEn: "Bachelor of Medicine and Surgery",
      descriptionAr: "<p>برنامج طبي متكامل يربط العلوم الطبية الأساسية بالتدريب السريري وأخلاقيات الممارسة والبحث الصحي.</p>",
      descriptionEn: "<p>An integrated medical program connecting basic medical sciences with clinical training, practice ethics, and health research.</p>",
      internshipAr: "<p>يشمل البرنامج تدريبا سريريا متدرجا وتطبيقات محاكاة وممارسة تحت إشراف أكاديمي ومهني.</p>",
      internshipEn: "<p>The program includes progressive clinical training, simulation applications, and supervised academic and professional practice.</p>",
      status: "published",
    },
    {
      collegeId: pharmacy.id,
      nameAr: "بكالوريوس الصيدلة",
      nameEn: "BPharm Pharmacy",
      slug: "bpharm-pharmacy",
      level: "bachelor",
      durationYears: 5,
      tuitionFees: 82000,
      currency: "EGP",
      programCode: "EUST-PHAR-BPH",
      coordinatorName: "Pharmacy Program Coordinator",
      coordinatorEmail: "pharmacy.program@eust.uk",
      ...programAcademicProfile,
      descriptionAr: "<p>برنامج في علوم الدواء والرعاية الصيدلية والجودة والتصنيع وسلامة استخدام الأدوية.</p>",
      descriptionEn: "<p>A program in pharmaceutical sciences, pharmacy care, quality, manufacturing, and medication safety.</p>",
      careerOpportunitiesAr: "<ul><li>صيدلي مجتمعي</li><li>صيدلي إكلينيكي</li><li>مختص جودة دوائية</li><li>باحث في الصناعات الدوائية</li></ul>",
      careerOpportunitiesEn: "<ul><li>Community Pharmacist</li><li>Clinical Pharmacist</li><li>Pharmaceutical Quality Specialist</li><li>Pharmaceutical Industry Researcher</li></ul>",
      status: "published",
    },
    {
      collegeId: physiotherapy.id,
      nameAr: "بكالوريوس العلاج الطبيعي",
      nameEn: "BSc Physiotherapy",
      slug: "bsc-physiotherapy",
      level: "bachelor",
      durationYears: 5,
      tuitionFees: 74000,
      currency: "EGP",
      programCode: "EUST-PHYT-BSC",
      coordinatorName: "Physiotherapy Program Coordinator",
      coordinatorEmail: "physiotherapy.program@eust.uk",
      ...programAcademicProfile,
      descriptionAr: "<p>برنامج يؤهل الطلاب في علوم الحركة، التأهيل، العلاج الطبيعي للحالات العضلية والعصبية، والتواصل مع المرضى.</p>",
      descriptionEn: "<p>A program preparing students in movement sciences, rehabilitation, musculoskeletal and neurological physiotherapy, and patient communication.</p>",
      status: "published",
    },
    {
      collegeId: readings.id,
      nameAr: "بكالوريوس القراءات وعلوم القرآن",
      nameEn: "BA Quranic Readings and Sciences",
      slug: "ba-quranic-readings-sciences",
      level: "bachelor",
      durationYears: 4,
      tuitionFees: 34000,
      currency: "EGP",
      programCode: "EUST-READ-BA",
      coordinatorName: "Readings Program Coordinator",
      coordinatorEmail: "readings.program@eust.uk",
      ...programAcademicProfile,
      descriptionAr: "<p>برنامج متخصص في القراءات، علوم القرآن، الرسم والضبط، الأداء، ومهارات البحث في الدراسات القرآنية.</p>",
      descriptionEn: "<p>A specialized program in Quranic readings, Quranic sciences, orthography and accuracy, recitation performance, and Quranic studies research skills.</p>",
      status: "published",
    },
  ]);

  await insertSeed(facultyTable, [
    { collegeId: ai.id, nameAr: "د. ندى إبراهيم", nameEn: "Dr. Nada Ibrahim", titleAr: "أستاذ مساعد", titleEn: "Assistant Professor", specialization: "Artificial Intelligence", email: "n.ibrahim@eust.uk" },
    { collegeId: islamic.id, nameAr: "د. عمر خليل", nameEn: "Dr. Omar Khalil", titleAr: "أستاذ مشارك", titleEn: "Associate Professor", specialization: "Islamic Studies", email: "o.khalil@eust.uk" },
    { collegeId: business.id, nameAr: "د. مريم حسن", nameEn: "Dr. Mariam Hassan", titleAr: "مدرس", titleEn: "Lecturer", specialization: "Business Administration", email: "m.hassan@eust.uk" },
    { collegeId: nursing.id, nameAr: "د. يوسف سمير", nameEn: "Dr. Youssef Samir", titleAr: "أستاذ مساعد", titleEn: "Assistant Professor", specialization: "Nursing Practice", email: "y.samir@eust.uk" },
    { collegeId: languages.id, nameAr: "د. ليلى منصور", nameEn: "Dr. Laila Mansour", titleAr: "أستاذ مساعد", titleEn: "Assistant Professor", specialization: "Translation and Interpretation", email: "l.mansour@eust.uk" },
  ]);

  await insertSeed(newsTable, [
    {
      titleAr: "افتتاح مركز الابتكار وريادة الأعمال",
      titleEn: "Innovation and Entrepreneurship Center Opens",
      slug: "innovation-center-opens",
      type: "news",
      featured: 1,
      status: "published",
      publishedAt: now,
      summaryAr: "أطلقت الجامعة مركزا جديدا لدعم مشاريع الطلاب والشركات الناشئة.",
      summaryEn: "The university launched a new center to support student projects and startups.",
      contentAr: "<p>يقدم المركز برامج إرشاد ومساحات عمل وورش تدريب للطلاب.</p>",
      contentEn: "<p>The center provides mentoring, workspaces, and training workshops for students.</p>",
    },
    {
      titleAr: "ملتقى التوظيف السنوي 2026",
      titleEn: "Annual Career Fair 2026",
      slug: "career-fair-2026",
      type: "event",
      featured: 1,
      status: "published",
      publishedAt: now,
      eventDate: "2026-11-12",
      summaryAr: "تستضيف الجامعة أكثر من 60 جهة توظيف في ملتقى التوظيف السنوي.",
      summaryEn: "The university hosts more than 60 employers in the annual career fair.",
      contentAr: "<p>يتيح الملتقى مقابلات مباشرة وفرص تدريب وتوظيف للطلاب والخريجين.</p>",
      contentEn: "<p>The fair offers interviews, internships, and employment opportunities for students and graduates.</p>",
    },
    {
      titleAr: "مؤتمر البحث العلمي والتحول الرقمي",
      titleEn: "Research and Digital Transformation Conference",
      slug: "research-digital-transformation",
      type: "conference",
      featured: 0,
      status: "published",
      publishedAt: now,
      eventDate: "2026-12-05",
      summaryAr: "مؤتمر علمي يجمع الباحثين لمناقشة تطبيقات التحول الرقمي في التعليم.",
      summaryEn: "A research conference discussing digital transformation applications in education.",
      contentAr: "<p>يتضمن المؤتمر جلسات علمية وملصقات بحثية وورش عمل.</p>",
      contentEn: "<p>The conference includes scientific sessions, research posters, and workshops.</p>",
    },
  ]);

  await insertSeed(faqsTable, [
    {
      questionAr: "كيف أقدم للجامعة؟",
      questionEn: "How do I apply?",
      answerAr: "يمكنك التقديم من صفحة القبول والتسجيل واختيار البرنامج المناسب.",
      answerEn: "You can apply through the admissions page and select your preferred program.",
      category: "admissions",
      sortOrder: 1,
    },
    {
      questionAr: "هل توجد منح دراسية؟",
      questionEn: "Are scholarships available?",
      answerAr: "نعم، توجد منح للتفوق الأكاديمي والاحتياج الاجتماعي والأنشطة المتميزة.",
      answerEn: "Yes, scholarships are available for academic excellence, financial need, and outstanding activities.",
      category: "financial",
      sortOrder: 2,
    },
    {
      questionAr: "هل يمكن تعديل بيانات الطلب بعد الإرسال؟",
      questionEn: "Can I edit my application after submission?",
      answerAr: "يمكنك التواصل مع مكتب القبول لتحديث بياناتك قبل موعد غلق التقديم.",
      answerEn: "You can contact the admissions office to update your information before the application deadline.",
      category: "admissions",
      sortOrder: 3,
    },
  ]);
}

async function main() {
  await upsertSettings();
  await seedPageContent();
  await seedAcademicData();
  console.log("University demo content seeded successfully.");
}

main().catch((error) => {
  console.error(error);
  process.exitCode = 1;
});




